export const GPs = [
    {  
        currentGp: "Hungarian Grand Prix",
        reference: new Date("July 18, 2024").getDate(),
        firstGpDate: new Date("July 19, 2024").getDate(),
        secondGpDate: new Date("July 20, 2024").getDate(),
        thirdGpDate: new Date("July 21, 2024").getDate(),
    },
    {
        currentGp: "Belgium Grand Prix",
        reference: new Date("July 25, 2024").getDate(),
        firstGpDate: new Date("July 26, 2024").getDate(),
        secondGpDate: new Date("July 27, 2024").getDate(),
        thirdGpDate: new Date("July 28, 2024").getDate(),
    },
    {
        currentGp: "Dutch Grand Prix",
        reference: new Date("August 22, 2024").getDate(),
        firstGpDate: new Date("August 23, 2024").getDate(),
        secondGpDate: new Date("August 24, 2024").getDate(),
        thirdGpDate: new Date("August 25, 2024").getDate(),
    },
    {
        currentGp: "Italian Grand Prix",
        reference: new Date("August 29, 2024").getDate(),
        firstGpDate: new Date("August 30, 2024").getDate(),
        secondGpDate: new Date("September 31, 2024").getDate(),
        thirdGpDate: new Date("September 01, 2024").getDate(),
    },
    {
        currentGp: "Azerbaijan Grand Prix",
        reference: new Date("September 12, 2024").getDate(),
        firstGpDate: new Date("September 13, 2024").getDate(),
        secondGpDate: new Date("September 14, 2024").getDate(),
        thirdGpDate: new Date("September 15, 2024").getDate(),
    },
    {
        currentGp: "Singapore Grand Prix",
        reference: new Date("September 19, 2024").getDate(),
        firstGpDate: new Date("September 20, 2024").getDate(),
        secondGpDate: new Date("September 21, 2024").getDate(),
        thirdGpDate: new Date("September 22, 2024").getDate(),
    },
    {
        currentGp: "USA Grand Prix",
        reference: new Date("October 17, 2024").getDate(),
        firstGpDate: new Date("October 18, 2024").getDate(),
        secondGpDate: new Date("October 19, 2024").getDate(),
        thirdGpDate: new Date("October 20, 2024").getDate(),
    },
    {
        currentGp: "Mexican Grand Prix",
        reference: new Date("October 24, 2024").getDate(),
        firstGpDate: new Date("October 25, 2024").getDate(),
        secondGpDate: new Date("October 26, 2024").getDate(),
        thirdGpDate: new Date("October 27, 2024").getDate(),
    },
    {
        currentGp: "Brazilian Grand Prix",
        reference: new Date("October 30, 2024").getDate(),
        firstGpDate: new Date("November 01, 2024").getDate(),
        secondGpDate: new Date("November 02, 2024").getDate(),
        thirdGpDate: new Date("November 03, 2024").getDate(),
    },
    {
        currentGp: "Las Vegas Grand Prix",
        reference: new Date("November 20, 2024").getDate(),
        firstGpDate: new Date("November 21, 2024").getDate(),
        secondGpDate: new Date("November 22, 2024").getDate(),
        thirdGpDate: new Date("November 23, 2024").getDate(),
    },
    {
        currentGp: "Qatar Grand Prix",
        reference: new Date("November 28, 2024").getDate(),
        firstGpDate: new Date("November 29, 2024").getDate(),
        secondGpDate: new Date("November 30, 2024").getDate(),
        thirdGpDate: new Date("December 01, 2024").getDate(),
    },
    {
        currentGp: "Abu Dhabi Grand Prix",
        reference: new Date("December 05, 2024").getDate(),
        firstGpDate: new Date("December 06, 2024").getDate(),
        secondGpDate: new Date("December 07, 2024").getDate(),
        thirdGpDate: new Date("December 08, 2024").getDate(),
    },
]